spring.application.name=portfolio-be
spring.profiles.active=dev

# Configurazioni JWT (I valori reali sono nei file dei profili ignorati da Git)
app.jwt-expiration-milliseconds=${JWT_EXPIRATION:3600000}
app.jwt-secret=${JWT_SECRET}